version: "3.8"

services:
  web_hood:
    build: .
    command: gunicorn hood_blast.wsgi:application --bind 0.0.0.0:8005 --workers 1
    volumes:
      - .:/usr/src/hood_blast/
    ports:
      - 8005:8005
    env_file:
      - ./.env
    depends_on:
      - db_hood
  db_hood:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_hood:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frank
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hoodblast
    ports:
      -5434:5432
volumes:
  postgres_data_hood:

