# Generated by Django 4.0.3 on 2022-03-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='neighbourhood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='hoods.neighbourhood'),
        ),
    ]
